Repository CS2103JAN2018-T11-B3/main, pull requests merged in 2018-03, with the labels that each got.

#27 [V1.2] Insurance tag colour
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Insurance/Insurance.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: enhancement

#30 Added description of Notification enhancement
  docs/DeveloperGuide.adoc
Labels: Documentation

#28 Add Appointments
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentNotFoundException.java
  src/main/java/seedu/address/model/appointment/exceptions/DuplicateAppointmentException.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: enhancement

#68 added demo image for client
  src/main/resources/images/test.jpg
  src/main/resources/view/PersonListCard.fxml
Labels: type.enhancement

#69 updated typical person, and standard data test to at least make test run
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.updateTest
